#!/usr/bin/env node
/**
 * Renders a 1200x630 branded card to PNG via headless Chrome.
 *
 * Used for the site's static OG image and, later, for per-post social
 * images generated by the content engine. Slots are filled by id:
 * eyebrow, headline, sub, footleft, footright.
 *
 *   node scripts/render-card.mjs --out public/og.png
 *   node scripts/render-card.mjs --out /tmp/post.png \
 *     --headline 'Dam levels crossed <em>82%</em> this week' \
 *     --eyebrow 'Dam Watch · 11 Aug 2026'
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SLOTS = ['eyebrow', 'headline', 'sub', 'footleft', 'footright']
const CHROME = process.env.CHROME_BIN || 'google-chrome'

const args = process.argv.slice(2)
const opts = {}
for (let i = 0; i < args.length; i += 2) {
  if (!args[i].startsWith('--')) throw new Error(`expected a --flag, got: ${args[i]}`)
  opts[args[i].slice(2)] = args[i + 1]
}

const out = resolve(opts.out || 'public/og.png')
let html = readFileSync(join(HERE, 'card-template.html'), 'utf8')

for (const slot of SLOTS) {
  if (opts[slot] === undefined) continue
  // Replace the element's inner HTML. The backreference to the tag name is
  // load-bearing: slots whose default markup contains a nested tag (the
  // headline's <em>) would otherwise terminate on that inner closing tag and
  // leave the tail of the default text behind.
  const re = new RegExp(`(<(\\w+)[^>]*\\bid="${slot}"[^>]*>)[\\s\\S]*?(</\\2>)`)
  if (!re.test(html)) throw new Error(`template has no slot #${slot}`)
  html = html.replace(re, `$1${opts[slot]}$3`)
}

const work = mkdtempSync(join(tmpdir(), 'kx-card-'))
const page = join(work, 'card.html')
writeFileSync(page, html)

mkdirSync(dirname(out), { recursive: true })
execFileSync(CHROME, [
  '--headless',
  '--disable-gpu',
  '--no-sandbox',
  '--hide-scrollbars',
  '--force-device-scale-factor=1',
  '--window-size=1200,630',
  `--screenshot=${out}`,
  `file://${page}`,
], { stdio: 'inherit' })

console.log(`rendered ${out}`)
